dd= ["Prefiero morir antes de dejar de prepararte un rico y delicioso café",
"Mi objetivo es ser el mejor preparador de cafes de todo habbo.",
"La unica razon de mi existencia es que tu mi querido amigo, bebas un delicioso café",
"Los cafés que yo preparo son dignos de un dios.",
"Mis cafés contienen aguas de las mismísimas fuentes de los dioses.",
"Amo servir cafés, prefiero morir antes dejar servir ricos cafés.",
"Los cafés que yo sirvo son extramadamente deliciosos.",
"Solo un finísimo caballero y excelsa dama como tu, se merece un café de esta magnitud.",
"Mis cafés son los mejores cafés de todo Habbo hotel.",
"Los granos con que se preparan estos cafés, vienen de mismisimas montañas de Asgard.",
"No hay palabra alguna para describir lo enormemente deliciosos que son mis cafés ",
"Los cafés que preparo yo son indescriptibles, un sabor infinitamente delicioso.",
"El café que he preparado para ti, es un café digno de una deidad suprema",
"Espero con todo fervor que disfrutes esta maravilla de café que he preparado para ti",
"Aqui tienes un delicioso cafe, digno de todo un aristocrata",
"Mi unico objetivo en este mundo es preparar un café para ti mi estimado colega",
"Prepararte un café es mi deber, y yo lo cumplo con todo fervor",
"Estoy aqui solamente para que tu, finísimo caballero e inmaculada dama disfruten de un rico café",
"Do you folks like coffee?, Real coffee, From the hills of Colombia.",
"Servirte un delicioso café me hace sentir vivo, me da alegria y pasion ",
"Preparar esquizitos cafés es mi deber",
"Mi sueño es preparar los mejores cafés de todo habbo",
"Este café que te he preparado esta de rechupete",
"Este café que te he preparado sabe a gloria",
"El sabor de este café que te preparé es de niveles divinos",
"Preparar un cafe para ti es el mayor placer de toda la existencia",
"Servir ricos cafés es una experiencia sublime, unica e incomparable",
"Mi mayor placer es que tu honorable ser viviente disfrutes de este incomparable café",
"Quieres café?, la paciencia es una virtud mi estimado, ya te llega, calma...",
"Espero con toda vehemencia que al beber este café te regocijes de placer",
"Este café que te voy a preparar es digno de un emperador",
"Me siento muy orgulloso de preparar cafés, tanto que prefiero morir a dejar de hacerlo",
"Lo unico que tiene sentido para mi en este universo es servirte un sabroso café",
"los cafés que yo preparo son exquisitos, suculentos, sublimes, épicos, dignos de los dioses",
"Preparar café y bebidas es mi vida, es para lo unico que vivo",
"Para mi prepararte café a ti, esta por encima de cualquier cosa posible",
"Yo honro la existencia de la humanidad preparando café",
"Un finísimo caballero y una excelsa dama como tu se merece un café de los dioses",
"Este café que he prepardo es suculento",
"Acabo de probar este cafe que prepare y QUE DELICIA!, DIOS QUE MARAVILLA!",
"Este café es tan exquisito que es digno de un guerrero del Valhalla",
"El brillo de mi cabeza es sublime, pero no tanto como este sabroso café capuccino",
"Esto es Café de los dioses"]



#print(len(dd))